modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="thaumcraft"
version="0.3"
displayName="Thaumcraft (Private Port)"
authors="Smile_112"
description=Internal private port for personal use

[[dependencies.thaumcraft]]
modId="forge"
mandatory=true
versionRange="[47,)"

[[dependencies.thaumcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"

# Soft dependency on Curios
[[dependencies.thaumcraft]]
modId="curios"
mandatory=false
versionRange="*"
ordering="NONE"
side="BOTH"