modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="thaumcraft"
version="${file.jarVersion}"
displayName="Thaumcraft (Private Port)"
authors="Smile_112"
description="Internal private port for personal use"

[[dependencies.thaumcraft]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.thaumcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

# soft-dep Curios
[[dependencies.thaumcraft]]
modId="curios"
mandatory=false
versionRange="*"
ordering="AFTER"
side="BOTH"