name: build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew || true
      - name: Build
        run: ./gradlew --no-daemon build
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thaumcraft-port-build
          path: |
            build/libs/*.jar
            */build/libs/*.jar
