modLoader="javafml"
loaderVersion="[47, )"
license="All Rights Reserved"

[[mods]]
modId="thaumcraft"
version="${mod_version}"
displayName="Thaumcraft"
authors="Azanor"
description='''Thaumcraft port for Minecraft 1.20.1.'''

[[dependencies.thaumcraft]]
modId="forge"
mandatory=true
versionRange="[47, )"
ordering="NONE"
side="BOTH"

[[dependencies.thaumcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
