name: build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Устанавливаем Gradle без wrapper
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build mod
        working-directory: port-1.20.1
        run: gradle --no-daemon build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: thaumcraft-port-build
          path: port-1.20.1/build/libs/*.jar
